inherit_from: .rubocop_todo.yml



require:
  - rubocop-rails
  - rubocop-rspec

# 対象外
AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - "db/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "lib/**/*"
    - "Gemfile"
    - "config/**/*"
    - "app/channels/application_cable/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.6

# trueかfalseを設定しないと警告が出る
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

##################### Style ##################################

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

# 明示的に else で nil を返すのは分かりやすいので許可する
Style/EmptyElse:
  EnforcedStyle: empty

# https://www.task-notes.com/entry/20160831/1472572735
Style/FrozenStringLiteralComment:
  Enabled: false

# if/unless内の処理が4行以上のときのみにする
Style/GuardClause:
  MinBodyLength: 4

# do .. end から更にメソッドチェーンすると見にくいので
# auto-correct せず、自分で修正する
# spec 内は見た目が綺麗になるので許可
Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

##################### Lint ##################################

# * 同名のメソッドがある場合にローカル変数に `_` を付ける
# * 一時変数として `_` を付ける
# というテクニックは頻出する
Lint/UnderscorePrefixedVariableName:
  Enabled: false

##################### Layout ###################################

# メソッドチェーンの改行は末尾に . を入れる
# REPL に貼り付けた際の暴発を防ぐため
Layout/DotPosition:
  EnforcedStyle: trailing

# private/protected は一段深くインデントする
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# 1行の文字数
Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

##################### Metrics ##################################

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# RSpecのみ1ブロックあたりの行数超過を許可
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

##################### RSpec ##################################
# 1exampleの行数
# デフォルトだと厳しすぎる
RSpec/ExampleLength:
  Max: 10

# デフォルト : Start context description with 'when', 'with', or 'without'.
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - as

# グループ(describeやcontext)のネスト
# 3だと厳しい
RSpec/NestedGroups:
  Max: 4

# 1exampleあたりのエクスペクテーションの数
# パフォーマンスの問題さえなければ1example 1expectationの方が良い
# aggregate_failuresを使う場合等を考慮すると1は厳しい
RSpec/MultipleExpectations:
  Max: 4

##################### Railsチュートリアル 一時無視 ##################################

Naming/AccessorMethodName:
  Enabled: false

# バリデーションをスキップするメソッドは警告が出る
# update_attribute等
Rails/SkipsModelValidations:
  Enabled: false

# ヘルパーメソッドでインスタンス変数を使わないこと
# Railsチュートリアルでは@current_userでガッツリ使ってしまっているので無視する
Rails/HelperInstanceVariable:
  Enabled: false

# 双方向の関連付けで inverse_of を指定する必要がある
Rails/InverseOf:
  Enabled: false

# &.演算子
Style/SafeNavigation:
  Enabled: false

# インスタンス変数の使用は避けること
# 今回は除外するが、今後は極力避ける
RSpec/InstanceVariable:
  Enabled: false